services:
  api:
    container_name: api
    ports:
      - "8000:8000"
    build:
      context: api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
    - redis

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A celery_client.tasks worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - api